# Generated by Django 4.2.21 on 2025-05-31 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cost',
        ),
    ]
