# Generated by Django 4.2.21 on 2025-05-31 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
