# Generated by Django 4.2.21 on 2025-06-02 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0013_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
