# Generated by Django 4.2.21 on 2025-06-02 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0093_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
