# Generated by Django 4.2.21 on 2025-06-02 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0105_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
